#!/usr/bin/env python3
"""Write src/pressless/_flag_data.py from a copy of the flag-icons package.

    python3 scripts/make_flags.py <unpacked flag-icons package folder>

flag-icons (https://github.com/lipis/flag-icons, MIT) is fetched by hand, as
npm's tarball, and unpacked anywhere outside the repository; this reads its
flags/4x3/*.svg and country.json. Only two-letter codes are kept: Insights
hands the dashboard ISO 3166-1 alpha-2 codes and nothing else (PRESS-0020).

The pictures are packed into a Python module rather than shipped as files, so
PyInstaller carries them with no change to the packaging flags (PRESS-0022).
"""
from __future__ import annotations

import base64
import json
import re
import sys
import zlib
from pathlib import Path

TARGET = Path(__file__).resolve().parent.parent / "src" / "pressless" / "_flag_data.py"
WIDTH = 96


def main(argv: list[str]) -> int:
    if len(argv) != 1:
        print(__doc__.strip().splitlines()[2].strip(), file=sys.stderr)
        return 2
    package = Path(argv[0])
    meta = json.loads((package / "package.json").read_text(encoding="utf-8"))
    names = {entry["code"]: entry["name"]
             for entry in json.loads((package / "country.json").read_text(encoding="utf-8"))}
    pictures = {}
    for path in sorted((package / "flags" / "4x3").glob("*.svg")):
        if re.fullmatch(r"[a-z]{2}", path.stem) and path.stem in names:
            pictures[path.stem.upper()] = path.read_text(encoding="utf-8")
    packed = base64.b64encode(zlib.compress(
        json.dumps(pictures, sort_keys=True, separators=(",", ":")).encode("utf-8"), 9)).decode()
    licence = (package / "LICENSE").read_text(encoding="utf-8").strip()

    out = ['"""Flag pictures and country names, generated by scripts/make_flags.py.',
           "",
           f"From flag-icons {meta['version']} (https://github.com/lipis/flag-icons),",
           "used under its licence, which follows. Do not edit; regenerate.",
           ""]
    out += [line.rstrip() for line in licence.splitlines()]
    out += ['"""', "", "NAMES = {"]
    out += [f"    {code.upper()!r}: {names[code]!r},"
            for code in sorted(c.lower() for c in pictures)]
    out += ["}", "", "# zlib-compressed JSON, base64: {code: SVG text}.", "PACKED = ("]
    out += [f'    "{packed[i:i + WIDTH]}"' for i in range(0, len(packed), WIDTH)]
    out += [")", ""]
    TARGET.write_text("\n".join(out), encoding="utf-8")
    print(f"Wrote {len(pictures)} flags to {TARGET}.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
