#!/usr/bin/env python3
"""Write the Google client secret into the program -- PRESS-0122 § 4.7.

    python3 scripts/write_google_secret.py [path]

Writes src/pressless/_google_secret.py (or <path>), which .gitignore names so
it is never committed. The value comes from the environment variable
GOOGLE_CLIENT_SECRET, as in a release job; where that is unset and this runs
in a terminal, it asks for it without showing what is typed.

Refuses, writing nothing, a value that is empty or holds anything but ASCII
letters, digits, '-' and '_'. Never prints the value.
"""
from __future__ import annotations

import getpass
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT = ROOT / "src" / "pressless" / "_google_secret.py"
_SHAPE = re.compile(r"[A-Za-z0-9_-]+")


def main(argv: list[str]) -> int:
    target = Path(argv[0]) if argv else DEFAULT
    value = os.environ.get("GOOGLE_CLIENT_SECRET")
    if value is None:
        value = getpass.getpass("Google client secret: ") if sys.stdin.isatty() else ""
    if not _SHAPE.fullmatch(value):
        print("No usable client secret: it must be non-empty and hold only letters, "
              "digits, '-' and '_'. Nothing was written.", file=sys.stderr)
        return 1
    target.write_text("# Generated by scripts/write_google_secret.py -- never committed.\n"
                      f"CLIENT_SECRET = {value!r}\n", encoding="utf-8")
    print(f"Wrote the client secret to {target}.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
